[build]
builder = "nixpacks"
buildCommand = "cd backend && yarn install && yarn build"

[deploy]
startCommand = "cd backend && yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "9000"
